### ISSUE TITLE
Editing notes in raindrop causes duplicates

### ISSUE THREAD

**Issue by cjfagerstrom** [phildenhoff/logseq-raindrop#84] opened 2023-11-09 17:15 UTC
If I edit notes saved on a raindrop logseq ends up with an article with the old raindrop notes and a second one with the edits.

**Comment by phildenhoff** [comment] 2023-11-09 17:17
Duplicate of #52 (and a very reasonable request)

**Closed by phildenhoff** 2023-11-09 17:17 UTC
Labels: bug, enhancement
